ALTER TABLE denuncias ADD COLUMN IF NOT EXISTS dependencia_remitida VARCHAR(255) DEFAULT NULL;
ALTER TABLE denuncias ADD COLUMN IF NOT EXISTS remitido_por VARCHAR(150) DEFAULT NULL;
ALTER TABLE denuncias ADD COLUMN IF NOT EXISTS remitido_en TIMESTAMP WITH TIME ZONE DEFAULT NULL;
